### PR TITLE
Add unit testing with GitHub actions (linux, macos and windows)

### PR DESCRIPTION
**Pull request by alexamici**
After Travis-CI has changed its terms of service several Open Source projects are moving to GitHub Actions.

This PR adds tests with GitHub actions and remove Travis-CI.

~Note that the code-style workflows fails due to a few trivial black failures. They can be fixed in a different PR.~ (fixed by installing the version of black in conda-forge, not defaults)

Windows write unit tests fail mostly due to a problem with the template folder.

### CODE REVIEW

**Comment by shahramn** [comment]
Dear Alessandro,
I would like to keep the Travis stuff for now. Can you re-submit your PR without the travis yaml deletion please?

**Review by shahramn — CHANGES_REQUESTED** [review]
Dear Alessandro,
I would like to keep the Travis stuff for now. Can you re-submit your PR without the travis yaml deletion please

**Comment by alexamici** [comment]
@shahramn apparently I don't have write permission to the repo anymore, so I can't update the files in branch and thus the PR.

This appears to be a recent change as I did create the branch and the PR by pushing to the `eccodes-python` repo.

I can fork and create another PR later in the week.

**Comment by shahramn** [comment]
I have merged this to a separate branch which will later be merged to develop

**Pull request merged**
