### PR TITLE
Add support for remote url loading and already opened files

### PR DESCRIPTION
**Pull request by lopes-gustavo**

### CODE REVIEW

**Comment by lopes-gustavo** [comment]
I still need to write tests and make it work with python2

**Comment by alexamici** [comment]
@lopes-gustavo you don't need to support python2, the project is python 3 only.

I like the support to read from already opened files, but I don't like the remote URL part as it requires to depend from `requests` that is a *big* dependency.

I'd suggest you to split the URL support to a different PR.

@shahramn what's your opinion?

**Comment by shahramn** [comment]
I agree with Alessandro. We want to minimise the dependencies unless they are absolutely necessary

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf/eccodes-python?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf/eccodes-python?pullRequest=6) before we can accept your contribution.<br/><hr/>**Gustavo Lopes** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf/eccodes-python?pullRequest=6) it.</sub>

**Comment by lopes-gustavo** [comment]
I renamed my account, so I lost access to this repo.
The provided code is public, so if any of you want to merge it or use part of it, you can do it.
If you need me to do anything, please, don't hesitate to ask, I'll gladly help.

**Pull request closed without merging**
